// Generated by scripts/generate-nga-search-spotlights.ts.
// The content hash keeps the immutable CDN URL safe to cache indefinitely.
export const NGA_SEARCH_SPOTLIGHT_ASSET_PATH =
  '/search-spotlights/nga/v28-34970be6a9468e53e211d62abb04dd2140a626409ba3bc8a1ea7c67999e64905.json' as const;
