// Generated by scripts/generate-ngs-search-spotlights.ts.
export const NGS_SEARCH_SPOTLIGHT_API_PATH =
  '/orgs/ngs/search-spotlights/v32-5d8767ac75390c1f608d00ed8ee81676a1d37d26b1ed94d69cb32b078cc6b499' as const;
