// Generated by scripts/generate-nga-search-spotlights.ts.
// The content hash keeps the immutable CDN URL safe to cache indefinitely.
export const NGA_SEARCH_SPOTLIGHT_ASSET_PATH =
  '/search-spotlights/nga/v23-fadde3b1194dcfde97d5d0422ff94a270fdf8a3c92d67f87707f94a2251bd214.json' as const;
