// Generated by scripts/generate-nga-search-spotlights.ts.
// The content hash keeps the immutable CDN URL safe to cache indefinitely.
export const NGA_SEARCH_SPOTLIGHT_ASSET_PATH =
  '/search-spotlights/nga/v18-5644120a04f09c9d651106bd0f0bda52c2bb3fa14e965b84d9ba0f609776e01a.json' as const;
