import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it } from 'vitest';
import { CaptionSourceToggle } from './caption-source-toggle';

describe('CaptionSourceToggle', () => {
  it('defaults to Roots text and lets users switch to generated caption text', async () => {
    const user = userEvent.setup();

    render(
      <CaptionSourceToggle
        rootsCaption={{
          text: 'Roots catalogue text from the public record.',
          sourceLabel: 'Roots NHB',
        }}
        generatedCaption={{
          text: 'Generated visual caption for search.',
          sourceLabel: 'Generated by Paillette AI',
          details: [
            ['Model', 'mlx-community/Qwen3-VL-30B-A3B-Instruct-4bit'],
          ],
        }}
      />
    );

    expect(
      screen.getByText('Roots catalogue text from the public record.')
    ).toBeVisible();
    expect(
      screen.queryByText('Generated visual caption for search.')
    ).toBeNull();
    expect(
      screen.getByRole('button', { name: /^Roots$/ })
    ).toHaveAttribute('aria-pressed', 'true');

    await user.click(screen.getByRole('button', { name: /^Generated$/ }));

    expect(
      screen.getByText('Generated visual caption for search.')
    ).toBeVisible();
    expect(
      screen.queryByText('mlx-community/Qwen3-VL-30B-A3B-Instruct-4bit')
    ).toBeNull();
    expect(screen.queryByText('Model')).toBeNull();
    expect(screen.queryByText('Prompt')).toBeNull();
    expect(screen.queryByText('cap-ngs-missing-v1')).toBeNull();
    expect(
      screen.queryByText('Roots catalogue text from the public record.')
    ).toBeNull();
    expect(
      screen.getByRole('button', { name: /^Generated$/ })
    ).toHaveAttribute('aria-pressed', 'true');
  });

  it('shows generated captions alone with source provenance', () => {
    render(
      <CaptionSourceToggle
        generatedCaption={{
          text: 'Generated caption only.',
          sourceLabel: 'Generated by Paillette AI',
        }}
      />
    );

    expect(screen.getByText('Generated caption only.')).toBeVisible();
    expect(screen.getByLabelText(/Source: Generated caption:/)).toBeVisible();
    expect(
      screen.queryByRole('button', { name: /^Roots$/ })
    ).toBeNull();
    expect(
      screen.queryByRole('button', { name: /^Generated$/ })
    ).toBeNull();
  });

  it('promotes Roots text when it arrives after a generated-only caption', async () => {
    const { rerender } = render(
      <CaptionSourceToggle
        generatedCaption={{
          text: 'Generated caption first.',
          sourceLabel: 'Generated by Paillette AI',
        }}
      />
    );

    expect(screen.getByText('Generated caption first.')).toBeVisible();

    rerender(
      <CaptionSourceToggle
        rootsCaption={{
          text: 'Roots catalogue text loaded later.',
          sourceLabel: 'Roots NHB',
        }}
        generatedCaption={{
          text: 'Generated caption first.',
          sourceLabel: 'Generated by Paillette AI',
        }}
      />
    );

    await waitFor(() => {
      expect(
        screen.getByText('Roots catalogue text loaded later.')
      ).toBeVisible();
      expect(screen.queryByText('Generated caption first.')).toBeNull();
      expect(screen.getByRole('button', { name: /^Roots$/ })).toHaveAttribute(
        'aria-pressed',
        'true'
      );
    });
  });

  it('resets to Roots when the artwork caption set changes', async () => {
    const user = userEvent.setup();
    const { rerender } = render(
      <CaptionSourceToggle
        rootsCaption={{
          text: 'First Roots caption.',
          sourceLabel: 'Roots NHB',
        }}
        generatedCaption={{
          text: 'First generated caption.',
          sourceLabel: 'Generated by Paillette AI',
        }}
      />
    );

    await user.click(screen.getByRole('button', { name: /^Generated$/ }));
    expect(screen.getByText('First generated caption.')).toBeVisible();

    rerender(
      <CaptionSourceToggle
        rootsCaption={{
          text: 'Second Roots caption.',
          sourceLabel: 'Roots NHB',
        }}
        generatedCaption={{
          text: 'Second generated caption.',
          sourceLabel: 'Generated by Paillette AI',
        }}
      />
    );

    await waitFor(() => {
      expect(screen.getByText('Second Roots caption.')).toBeVisible();
      expect(screen.queryByText('Second generated caption.')).toBeNull();
      expect(screen.getByRole('button', { name: /^Roots$/ })).toHaveAttribute(
        'aria-pressed',
        'true'
      );
    });
  });
});
