import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it } from 'vitest';
import { CaptionSourceToggle } from './caption-source-toggle';

describe('CaptionSourceToggle', () => {
  it('defaults to Roots text and lets users switch to generated caption text', async () => {
    const user = userEvent.setup();

    render(
      <CaptionSourceToggle
        rootsCaption={{
          text: 'Roots catalogue text from the public record.',
          sourceLabel: 'Roots NHB',
        }}
        generatedCaption={{
          text: 'Generated visual caption for search.',
          sourceLabel: 'Generated by Paillette AI',
          details: [
            ['Model', 'mlx-community/Qwen3-VL-30B-A3B-Instruct-4bit'],
          ],
        }}
      />
    );

    expect(
      screen.getByText('Roots catalogue text from the public record.')
    ).toBeVisible();
    expect(
      screen.queryByText('Generated visual caption for search.')
    ).toBeNull();
    expect(
      screen.getByRole('button', { name: /^Roots catalogue$/ })
    ).toHaveAttribute('aria-pressed', 'true');

    await user.click(
      screen.getByRole('button', { name: /^Generated caption$/ })
    );

    expect(
      screen.getByText('Generated visual caption for search.')
    ).toBeVisible();
    expect(screen.getAllByText('Model')).toHaveLength(2);
    expect(
      screen.getAllByText('mlx-community/Qwen3-VL-30B-A3B-Instruct-4bit')
    ).toHaveLength(2);
    expect(screen.queryByText('Prompt')).toBeNull();
    expect(screen.queryByText('cap-ngs-missing-v1')).toBeNull();
    expect(
      screen.queryByText('Roots catalogue text from the public record.')
    ).toBeNull();
    expect(
      screen.getByRole('button', { name: /^Generated caption$/ })
    ).toHaveAttribute('aria-pressed', 'true');
  });

  it('shows generated captions alone with source provenance', () => {
    render(
      <CaptionSourceToggle
        generatedCaption={{
          text: 'Generated caption only.',
          sourceLabel: 'Generated by Paillette AI',
        }}
      />
    );

    expect(screen.getByText('Generated caption only.')).toBeVisible();
    expect(screen.getByLabelText(/Source: Generated caption:/)).toBeVisible();
    expect(
      screen.queryByRole('button', { name: /^Roots catalogue$/ })
    ).toBeNull();
    expect(
      screen.queryByRole('button', { name: /^Generated caption$/ })
    ).toBeNull();
  });
});
