import { render, screen } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import {
  getSourceIndicatorDetails,
  SourceIndicator,
} from './source-indicator';

describe('SourceIndicator', () => {
  it('labels NGS descriptions as catalogue/API provenance, not site text', () => {
    expect(getSourceIndicatorDetails('National Gallery Singapore')).toMatchObject({
      title: 'NGS catalogue',
      shortLabel: 'NGS',
      description:
        'Catalogue text imported from National Gallery Singapore collection/API data.',
    });
  });

  it('labels Roots and generated caption sources distinctly', () => {
    expect(getSourceIndicatorDetails('roots')).toMatchObject({
      title: 'Roots catalogue',
      shortLabel: 'Roots',
    });
    expect(getSourceIndicatorDetails('Generated by Paillette AI')).toMatchObject(
      {
        title: 'Generated caption',
        shortLabel: 'AI',
      }
    );
  });

  it('does not render a hover tooltip that can be clipped inside scroll panes', () => {
    render(<SourceIndicator label="National Gallery Singapore" showLabel />);

    const indicator = screen.getByLabelText(
      /Source: NGS catalogue: Catalogue text imported from National Gallery Singapore collection\/API data\./
    );

    expect(indicator).toHaveTextContent('NGS catalogue');
    expect(indicator).not.toHaveAttribute('title');
    expect(indicator).toHaveAttribute(
      'data-source-description',
      'NGS catalogue: Catalogue text imported from National Gallery Singapore collection/API data.'
    );
  });
});
