import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it } from 'vitest';
import { getSourceIndicatorDetails, SourceIndicator } from './source-indicator';

describe('SourceIndicator', () => {
  it('labels NGS descriptions as catalogue/API provenance, not site text', () => {
    expect(
      getSourceIndicatorDetails('National Gallery Singapore')
    ).toMatchObject({
      title: 'NGS catalogue',
      shortLabel: 'NGS',
      description:
        'Catalogue text imported from National Gallery Singapore collection/API data.',
    });
  });

  it('labels Roots and generated caption sources distinctly', () => {
    expect(getSourceIndicatorDetails('roots')).toMatchObject({
      title: 'Roots catalogue',
      shortLabel: 'Roots',
    });
    expect(
      getSourceIndicatorDetails('Generated by Paillette AI')
    ).toMatchObject({
      title: 'Generated caption',
      shortLabel: 'AI',
    });
  });

  it('opens provenance details from the source pill without a native title tooltip', async () => {
    const user = userEvent.setup();

    render(
      <SourceIndicator
        label="Generated by Paillette AI"
        showLabel
        details={[
          ['Model', 'mlx-community/Qwen3-VL-30B-A3B-Instruct-4bit'],
          ['Prompt', 'cap-ngs-missing-v1'],
        ]}
      />
    );

    const indicator = screen.getByRole('button', {
      name: /Source: Generated caption: Generated visual description with model provenance\./,
    });

    expect(indicator).toHaveTextContent('Generated caption');
    expect(indicator).not.toHaveAttribute('title');
    expect(indicator).toHaveAttribute(
      'data-source-description',
      'Generated caption: Generated visual description with model provenance.'
    );
    expect(indicator).toHaveAttribute('aria-expanded', 'false');

    await user.click(indicator);

    expect(indicator).toHaveAttribute('aria-expanded', 'true');
    expect(screen.getByRole('tooltip')).toHaveClass('visible');
    expect(screen.getByRole('tooltip')).not.toHaveClass('invisible');
    expect(
      screen.getByText('Generated visual description with model provenance.')
    ).toBeInTheDocument();
    expect(screen.getByText('Model')).toBeInTheDocument();
    expect(
      screen.getByText('mlx-community/Qwen3-VL-30B-A3B-Instruct-4bit')
    ).toBeInTheDocument();
    expect(screen.getByText('Prompt')).toBeInTheDocument();
    expect(screen.getByText('cap-ngs-missing-v1')).toBeInTheDocument();
  });

  it('keeps catalogue provenance available from the pill', () => {
    render(<SourceIndicator label="National Gallery Singapore" showLabel />);

    expect(
      screen.getByRole('button', {
        name: /Source: NGS catalogue: Catalogue text imported from National Gallery Singapore collection\/API data\./,
      })
    ).toHaveTextContent('NGS catalogue');
    expect(
      screen.getByText(
        'Catalogue text imported from National Gallery Singapore collection/API data.'
      )
    ).toBeInTheDocument();
  });
});
