import { createHash } from 'node:crypto';
import { mkdir, rename, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PUBLIC_SEARCH_CONTRACT_VERSION } from '@paillette/types/public-search';
import {
  generateNgsSpotlightBundle,
  type NgsSpotlightSearchRequest,
} from '../apps/web/app/lib/nga-spotlight-generator.server';
import type { ApiResponse, SearchResponse } from '../apps/web/app/types';

const getArgument = (name: string) => {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1]?.trim() : undefined;
};

const apiBaseUrl = getArgument('--api-base-url')?.replace(/\/+$/, '');
const corpusVersion = getArgument('--corpus-version');
const allowSearchRequests = process.argv.includes('--allow-search-requests');

if (!apiBaseUrl || !corpusVersion || !allowSearchRequests) {
  throw new Error(
    'Usage: pnpm --filter @paillette/web spotlights:ngs -- --api-base-url <url>/api/v1 --allow-search-requests --corpus-version <version>'
  );
}

const apiKey = process.env.PAILLETTE_PUBLIC_SEARCH_API_KEY;

const networkSearch = async ({
  provider,
  definitionId: _definitionId,
  ...request
}: NgsSpotlightSearchRequest): Promise<SearchResponse> => {
  const headers = new Headers({ 'Content-Type': 'application/json' });
  if (apiKey) {
    headers.set('X-API-Key', apiKey);
  } else {
    headers.set('X-User-Id', 'ngs-spotlight-generator');
    headers.set('X-User-Email', 'ngs-spotlight-generator@paillette.local');
    headers.set('X-User-Name', 'NGS Spotlight Generator');
  }

  const response = await fetch(
    `${apiBaseUrl}/orgs/${encodeURIComponent(provider)}/search/text`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify(request),
    }
  );
  const payload = (await response.json()) as ApiResponse<SearchResponse>;
  if (!response.ok || !payload.success || !payload.data) {
    throw new Error(
      `NGS spotlight search failed (${response.status}): ${payload.error?.message || 'unknown error'}`
    );
  }

  return payload.data;
};

const main = async () => {
  const { bundle, searchRequestCount } = await generateNgsSpotlightBundle({
    corpusVersion,
    search: networkSearch,
  });
  const serializedBundle = `${JSON.stringify(bundle)}\n`;
  const assetRevision = createHash('sha256')
    .update(serializedBundle)
    .digest('hex');
  const assetName = `ngs-search-spotlight-v${PUBLIC_SEARCH_CONTRACT_VERSION}-${assetRevision}.json`;
  const apiPath = `/orgs/ngs/search-spotlights/v${PUBLIC_SEARCH_CONTRACT_VERSION}-${assetRevision}`;

  const scriptDirectory = dirname(fileURLToPath(import.meta.url));
  const apiGeneratedDirectory = resolve(
    scriptDirectory,
    '..',
    'apps',
    'api',
    'src',
    'generated'
  );
  const outputPath = resolve(apiGeneratedDirectory, assetName);
  const apiRegistryPath = resolve(
    apiGeneratedDirectory,
    'ngs-search-spotlight-asset.ts'
  );
  const webRegistryPath = resolve(
    scriptDirectory,
    '..',
    'apps',
    'web',
    'app',
    'lib',
    'generated-ngs-search-spotlight-asset.ts'
  );
  const temporaryOutputPath = `${outputPath}.tmp`;
  const temporaryApiRegistryPath = `${apiRegistryPath}.tmp`;
  const temporaryWebRegistryPath = `${webRegistryPath}.tmp`;

  const apiRegistrySource = `// Generated by scripts/generate-ngs-search-spotlights.ts.\nimport bundle from './${assetName}';\n\nexport const NGS_SEARCH_SPOTLIGHT_ASSET_REVISION =\n  'v${PUBLIC_SEARCH_CONTRACT_VERSION}-${assetRevision}' as const;\nexport const NGS_SEARCH_SPOTLIGHT_BUNDLE = bundle;\n`;
  const webRegistrySource = `// Generated by scripts/generate-ngs-search-spotlights.ts.\nexport const NGS_SEARCH_SPOTLIGHT_API_PATH =\n  '${apiPath}' as const;\n`;

  await mkdir(apiGeneratedDirectory, { recursive: true });
  await writeFile(temporaryOutputPath, serializedBundle, 'utf8');
  await writeFile(temporaryApiRegistryPath, apiRegistrySource, 'utf8');
  await writeFile(temporaryWebRegistryPath, webRegistrySource, 'utf8');
  await rename(temporaryOutputPath, outputPath);
  await rename(temporaryApiRegistryPath, apiRegistryPath);
  await rename(temporaryWebRegistryPath, webRegistryPath);

  process.stdout.write(
    `Wrote ${outputPath} after ${searchRequestCount} authenticated search requests.\n`
  );
};

void main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`${message}\n`);
  process.exitCode = 1;
});
